# Generated by Django 3.2.12 on 2023-04-21 23:39

import datetime
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Column',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('column_name', models.CharField(max_length=100, verbose_name='Columna')),
                ('column_description', models.TextField(blank=True, null=True, verbose_name='DESCRIPCION')),
            ],
            options={
                'ordering': ['column_name'],
            },
        ),
        migrations.CreateModel(
            name='Help',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200, null=True, verbose_name='Titulo')),
                ('subtitle', models.CharField(blank=True, max_length=200, null=True, verbose_name='SubTitulo')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Descripción')),
            ],
            options={
                'verbose_name': 'Ayuda',
                'verbose_name_plural': 'Ayuda',
            },
        ),
        migrations.CreateModel(
            name='Meeting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre de la reunión')),
                ('fecha', models.DateTimeField()),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='Descripcion de la reunión')),
                ('start_time', models.CharField(blank=True, max_length=20, null=True, verbose_name='Hora Inicio')),
                ('end_time', models.CharField(blank=True, max_length=20, null=True, verbose_name='Hora Finalización')),
                ('objectives', models.TextField(blank=True, null=True, verbose_name='Objetivos')),
            ],
        ),
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
                ('is_admin', models.BooleanField(default=False, verbose_name='Jefe del Equipo')),
                ('meeting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backoffice.meeting')),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=100, verbose_name='Proyecto')),
                ('project_description', models.TextField(blank=True, null=True, verbose_name='DESCRIPCION')),
            ],
            options={
                'ordering': ['project_name'],
            },
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_name', models.CharField(max_length=100, verbose_name='Nombre del equipo')),
                ('team_description', models.TextField(verbose_name='Descripción y objetivos del equipo')),
                ('created', models.DateField()),
                ('active', models.BooleanField(default=True)),
                ('members', models.ManyToManyField(related_name='teams', through='backoffice.Membership', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['team_name'],
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_name', models.CharField(max_length=100, verbose_name='TAREA')),
                ('pool_evolucion', models.TextField(blank=True, verbose_name='Evolucion')),
                ('task_description', models.TextField(blank=True, null=True, verbose_name='DESCRIPCION')),
                ('compliance_date', models.DateTimeField(blank=True, default=datetime.datetime.now, null=True, verbose_name='FECHA DE CUMPLIMIENTO')),
                ('progreso', models.PositiveIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(100)])),
                ('on', models.BooleanField(default=True, verbose_name='Activar')),
                ('column', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backoffice.column', verbose_name='Columna')),
                ('created_by', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='CREADA POR')),
                ('owner_name', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='responsable', to=settings.AUTH_USER_MODEL, verbose_name='RESPONSABLE')),
                ('project', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='backoffice.project', verbose_name='Proyecto')),
            ],
            options={
                'ordering': ['compliance_date'],
            },
        ),
        migrations.CreateModel(
            name='Supercolumn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('supercolumn_name', models.CharField(max_length=100, verbose_name='Supercolumna')),
                ('supercolumn_description', models.TextField(blank=True, null=True, verbose_name='DESCRIPCION')),
                ('project', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='backoffice.project')),
            ],
            options={
                'ordering': ['supercolumn_name'],
            },
        ),
        migrations.AddField(
            model_name='membership',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backoffice.team'),
        ),
        migrations.AddField(
            model_name='membership',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='MeetingResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comentarios', models.TextField(blank=True)),
                ('completed', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('meeting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backoffice.meeting')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backoffice.task')),
            ],
        ),
        migrations.AddField(
            model_name='meeting',
            name='memberships',
            field=models.ManyToManyField(related_name='meetings', to='backoffice.Membership'),
        ),
        migrations.AddField(
            model_name='column',
            name='superior',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='backoffice.supercolumn', verbose_name='Superior'),
        ),
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_topic', models.CharField(max_length=30, verbose_name='ASUNTO:')),
                ('message_reference', models.CharField(blank=True, max_length=100, null=True, verbose_name='Previo')),
                ('message_text', models.TextField(blank=True, null=True, verbose_name='MENSAJE:')),
                ('message_date', models.DateTimeField(auto_now_add=True, null=True, verbose_name='FECHA:')),
                ('status', models.CharField(blank=True, choices=[('leido', 'leido'), ('para_recordar', 'para recordar'), ('sin leer', 'sin leer')], default='sin leer', max_length=31, null=True, verbose_name='Estado del mensaje')),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receiver', to=settings.AUTH_USER_MODEL, verbose_name='DESTINATARIO:')),
                ('sender', models.ForeignKey(default='0', on_delete=django.db.models.deletion.CASCADE, related_name='messages', to=settings.AUTH_USER_MODEL, verbose_name='CREADO POR:')),
            ],
            options={
                'ordering': ['message_date'],
            },
        ),
    ]
