# Generated by Django 3.2.12 on 2023-04-22 11:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backoffice', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='membership',
            name='meeting',
        ),
        migrations.RemoveField(
            model_name='meeting',
            name='memberships',
        ),
        migrations.AddField(
            model_name='meeting',
            name='memberships',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='backoffice.membership', verbose_name='Equipos'),
        ),
    ]
