# Generated by Django 3.2.12 on 2023-04-22 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backoffice', '0002_auto_20230422_1114'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='fechas',
            field=models.JSONField(default=dict, verbose_name='Fechas'),
        ),
    ]
