# Generated by Django 3.2.12 on 2023-04-23 01:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backoffice', '0003_task_fechas'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='fechas',
        ),
        migrations.AddField(
            model_name='task',
            name='fecha',
            field=models.DateTimeField(default=datetime.datetime(2023, 4, 23, 1, 34, 22, 241422)),
        ),
        migrations.AlterField(
            model_name='task',
            name='pool_evolucion',
            field=models.TextField(default='{}', verbose_name='Evolucion'),
        ),
    ]
