# Generated by Django 3.2.12 on 2023-04-23 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backoffice', '0004_auto_20230423_0134'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='fecha',
        ),
        migrations.AlterField(
            model_name='task',
            name='pool_evolucion',
            field=models.JSONField(default={}, verbose_name='Evolucion'),
        ),
    ]
