# Generated by Django 3.2.12 on 2023-04-23 23:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('backoffice', '0005_auto_20230423_2353'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='CREADA POR'),
        ),
        migrations.AlterField(
            model_name='task',
            name='pool_evolucion',
            field=models.JSONField(default='dict', verbose_name='Evolucion'),
        ),
    ]
