# Generated by Django 3.2.12 on 2023-04-23 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backoffice', '0006_auto_20230423_2354'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='pool_evolucion',
            field=models.JSONField(default='{}', verbose_name='Evolucion'),
        ),
    ]
