# Generated by Django 3.2.12 on 2023-04-24 11:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('backoffice', '0007_alter_task_pool_evolucion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='owner_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responsable', to=settings.AUTH_USER_MODEL, verbose_name='RESPONSABLE'),
        ),
        migrations.AlterField(
            model_name='task',
            name='pool_evolucion',
            field=models.JSONField(default=dict, verbose_name='Evolucion'),
        ),
    ]
