# Generated by Django 3.2.12 on 2023-04-25 14:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backoffice', '0009_project_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meeting',
            name='memberships',
        ),
        migrations.AddField(
            model_name='meeting',
            name='team',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='backoffice.team', verbose_name='Equipos'),
        ),
    ]
