# Generated by Django 3.2.12 on 2023-04-27 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backoffice', '0010_auto_20230425_1410'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='created_at',
            field=models.DateTimeField(default='2022-10-10'),
        ),
    ]
