# Generated by Django 3.2.12 on 2023-04-27 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backoffice', '0011_project_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meetingresult',
            name='comentarios',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='meetingresult',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='created_at',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='team',
            name='team_description',
            field=models.TextField(blank=True, null=True, verbose_name='Descripción y objetivos del equipo'),
        ),
    ]
